- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/NodeEncodingStrategyTests.swift
- XMLCoder.xcodeproj/project.pbxproj
This fixes a bug that would make `XMLEncoder` ignore the node-encoding strategy for values contained in unkeyed collections.
Given a set of types like this …
```swift
struct Foo: Codable {
var bar = Bar()
var unkeyedBars = [Bar()]
var keyedBars = ["foo": Bar()]
}
struct Bar: Codable {
let value = "baz"
static func nodeEncoding(forKey codingKey: CodingKey) -> XMLEncoder.NodeEncoding {
return .attribute
}
}
```
… and an encoder configured like this …
```swift
let encoder = XMLEncoder()
encoder.outputFormatting = .prettyPrinted
encoder.keyEncodingStrategy = .convertToSnakeCase
encoder.nodeEncodingStrategy = .custom { codableType, encoder in
guard let barType = codableType as? Bar.Type else {
return { _ in return .default }
}
return barType.nodeEncoding(forKey:)
}
```
… produces output that …
> Made sure node encoding strategy is considered for values inside unkeyed containers

- Sources/XMLCoder/Encoder/XMLEncoder.swift
- XMLCoder.xcodeproj/project.pbxproj
This should prevent a source-breaking change and allows next XMLCoder release only with a minor version bump.
> Add NodeEncodingStrategies typelias as deprecated

- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLDecodingStorage.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Sources/XMLCoder/Encoder/XMLEncodingStorage.swift
- Tests/XMLCoderTests/ArrayTest.swift
- Tests/XMLCoderTests/DictionaryTest.swift
- XMLCoder.xcodeproj/project.pbxproj
---
(A checkmark means the test runs successfully with the current implementation)
> Added unit tests for array and dictionary properties

- Sources/XMLCoder/Auxiliaries/XMLElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- XMLCoder.xcodeproj/project.pbxproj
This PR consists of mostly migrations from `if let` to `guard let` as well as other semantics-preserving changed to keep the conditional nesting low and make the control flow clear (i.e. the happy/expected path is the one with the least detours into `if` or `if let` blocks).
> Clean up `XMLStackParser`

- Sources/XMLCoder/Auxiliaries/ISO8601DateFormatter.swift
- Sources/XMLCoder/Auxiliaries/String+Extensions.swift
- Sources/XMLCoder/Auxiliaries/XMLElement.swift
- Sources/XMLCoder/Auxiliaries/XMLHeader.swift
- Sources/XMLCoder/Auxiliaries/XMLKey.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/DecodingErrorExtension.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLDecodingStorage.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Decoder/XMLUnkeyedDecodingContainer.swift
- Sources/XMLCoder/Encoder/EncodingErrorExtension.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Sources/XMLCoder/Encoder/XMLEncodingStorage.swift
- Sources/XMLCoder/Encoder/XMLKeyedEncodingContainer.swift
- Sources/XMLCoder/Encoder/XMLReferencingEncoder.swift
- Sources/XMLCoder/Encoder/XMLUnkeyedEncodingContainer.swift
As discussed in https://github.com/MaxDesiatov/XMLCoder/pull/19#discussion_r242742101.
> Remove use of explicit `internal`

- Sources/XMLCoder/Auxiliaries/XMLElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Box/KeyedBox.swift
- Sources/XMLCoder/Box/UnkeyedBox.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Sources/XMLCoder/Encoder/XMLKeyedEncodingContainer.swift
- Sources/XMLCoder/Encoder/XMLReferencingEncoder.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/Box/FloatBoxTests.swift
- Tests/XMLCoderTests/Box/KeyedBoxTests.swift
- Tests/XMLCoderTests/Box/UnkeyedBoxTests.swift
~Depends on #26 & #27.~ Not anymore.
This is a first attempt at making `_XMLElement` more approachable.
> Clean up `XMLElement`, `ArrayBox` & `DictionaryBox`

- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/Minimal/EmptyTests.swift
- XMLCoder.xcodeproj/project.pbxproj
By encoding via `func encode(_:withRootKey:header:)` we always get an XML root node with label `rootKey`, so not encoding anything within `func encode(to:)` is fine in XML (unlike JSON).
> Fixed a bug that would cause `XMLEncoder` to throw on `Encodable`s encoding nothing

- Sources/XMLCoder/Auxiliaries/XMLElement.swift
As `_XMLElement` was made a `struct` in 1f0cb9d91178678b64e251a5b761dbee7f519445, we can let the compiler synthesize `Equatable` conformance for free.
This PR removes the custom `_XMLElement: Equatable` conformance implementation.
> Let compiler synthesize Equatable conformance for _XMLElement

- Sources/XMLCoder/Box/KeyedBox.swift
- Sources/XMLCoder/Box/UnkeyedBox.swift
- Tests/XMLCoderTests/Box/BoolBoxTests.swift
- Tests/XMLCoderTests/Box/DataBoxTests.swift
- Tests/XMLCoderTests/Box/DateBoxTests.swift
- Tests/XMLCoderTests/Box/DecimalBoxTests.swift
- Tests/XMLCoderTests/Box/FloatBoxTests.swift
- Tests/XMLCoderTests/Box/IntBoxTests.swift
- Tests/XMLCoderTests/Box/KeyedBoxTests.swift
- Tests/XMLCoderTests/Box/NullBoxTests.swift
- Tests/XMLCoderTests/Box/StringBoxTests.swift
- Tests/XMLCoderTests/Box/UIntBoxTests.swift
- Tests/XMLCoderTests/Box/URLBoxTests.swift
- Tests/XMLCoderTests/Box/UnkeyedBoxTests.swift
… and remove unused internal methods to reduce the maintenance burden.
> Improve code coverage of box types

- .travis.yml
This should slightly decrease Travis build time for builds running from untagged commits.
> Install Carthage only in before_deploy on Travis

- Sources/XMLCoder/Auxiliaries/Metatypes.swift
- Sources/XMLCoder/Auxiliaries/XMLElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Decoder/XMLUnkeyedDecodingContainer.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/Minimal/UnkeyedTests.swift
- XMLCoder.xcodeproj/project.pbxproj
Also move protocols for tricks with metatypes to new Metatypes file.
Fix formatting of long lines in related files.
> Fix decoding of arrays with optional elements

- Tests/XMLCoderTests/ClassTests.swift
- Tests/XMLCoderTests/Minimal/IntTests.swift
- Tests/XMLCoderTests/Minimal/KeyedTests.swift
- XMLCoder.xcodeproj/project.pbxproj
Add tests to increase code coverage in Decoder files
> Increase test coverage

- Tests/XMLCoderTests/Minimal/IntTests.swift
Add test for keyd Int, Int8, Int16, Int32, Int64, UInt, UInt8, UInt16, UInt32, UInt64 types.
> Add test for keyed Int types

- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Tests/XMLCoderTests/ErrorContextTest.swift
- Tests/XMLCoderTests/ErrorContextTests.swift
> Add test to case when error context size goes outside content size

- Tests/XMLCoderTests/Minimal/BoolTests.swift
- Tests/XMLCoderTests/Minimal/DataTests.swift
- Tests/XMLCoderTests/Minimal/DateTests.swift
- Tests/XMLCoderTests/Minimal/DecimalTests.swift
- Tests/XMLCoderTests/Minimal/FloatTests.swift
- Tests/XMLCoderTests/Minimal/IntTests.swift
- Tests/XMLCoderTests/Minimal/StringTests.swift
- Tests/XMLCoderTests/Minimal/UIntTests.swift
- Tests/XMLCoderTests/Minimal/URLTests.swift
- Add test for Decode .keyFormatted
> Add tests to increase test coverage

- Sources/XMLCoder/Box/KeyedBox.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Decoder/XMLUnkeyedDecodingContainer.swift
- Tests/XMLCoderTests/BenchmarkTests.swift
- XMLCoder.xcodeproj/project.pbxproj
- XMLCoder.xcodeproj/xcshareddata/xcbaselines/XMLCoder::XMLCoderTests.xcbaseline/76E090BF-7AFE-4988-A06A-3C423396A4A4.plist
Admittedly the `_ closure: (() -> ()) -> ()` + `closure { … }` mumbo jumbo isn't the prettiest code I've ever written, but then again XCTest isn't a particularly usable testing framework either. 🤷🏻‍♂️
Xcode attaches the measurements popover to literal code occurrences of `self.measure { … }` itself, making the whole mess required in the first place. 🙄
(All while only supporting a single `self.measure { … }` per unit test. 🤦🏻‍♂️)
> Add dedicated benchmarking test suite

- Package.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Tests/XMLCoderTests/DynamicNodeEncodingTest.swift
When XMLCoder is compiled in Swift 5.0 mode it causes infinite loops in some tests, apparently due to change in `try?` behaviour introduced in [SE-0230](https://github.com/apple/swift-evolution/blob/master/proposals/0230-flatten-optional-try.md). In generic `unbox` handling of the `String` case with `try? unbox(box)` is always inferred as a call to `unbox<String?>` instead of a call to `unbox<String>`, as it was in Swift 4.2 mode. This is now fixed with rearranged type hints in this call. Also applied Swift 5.0 migrator suggestion to change `index` to `firstIndex`.
> Fix compatibility with Swift 5.0

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Tests/XMLCoderTests/AttributedIntrinsicTest.swift
Existing `flatten` implementation wasn't correctly handling element values, this is now fixed.
Fixes #78
> Fix nested attributed intrinsic

- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/NamespaceTest.swift
- XMLCoder.xcodeproj/project.pbxproj
This allows us to implement a fix for MaxDesiatov/CoreXLSX#41
> Add `shouldProcessNamespaces` decoder property

- Sources/XMLCoder/Auxiliaries/Box/KeyedBox.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Encoder/DynamicNodeEncoding.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/AttributedIntrinsicTest.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/BooksTest.swift
- Tests/XMLCoderTests/Box/KeyedBoxTests.swift
- Tests/XMLCoderTests/ClassTests.swift
- Tests/XMLCoderTests/DynamicNodeEncodingTest.swift
- Tests/XMLCoderTests/Minimal/UnkeyedIntTests.swift
> Ordered encoding

- .swiftformat
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Tests/XMLCoderTests/ErrorContextTest.swift
> Improve tests and fix error context handling

- .swiftformat
- README.md
- Sources/XMLCoder/Decoder/DynamicNodeDecoding.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Encoder/DynamicNodeEncoding.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Sources/XMLCoder/Encoder/XMLEncoderImplementation+SingleValueEncodingContainer.swift
- Tests/XMLCoderTests/DynamicNodeDecodingTest.swift
- Tests/XMLCoderTests/DynamicNodeEncodingTest.swift
- Tests/XMLCoderTests/SingleChildTests.swift
- XMLCoder.xcodeproj/project.pbxproj
This adds new `DynamicNodeDecoding` protocol similar to `DynamicNodeEncoding` introduced in #70
> Add DynamicNodeDecoding protocol

- .travis.yml
- Package@swift-4.2.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
The prevents linting stage from running multiple times in all parallel jobs. We're mostly going to develop with the latest version of Xcode, so we only care about linter and formatter warnings with that version. Thus, the linter stage runs first with the latest version, while actual tests run in parallel jobs of the next "test" stage.
> Add separate lint stage to .travis.yml

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
This PR uses a `map` over `key`-`value` pairs instead of `mapValues` along with `shuffled()`  when transforming attributes into a `Box`-ed representation within `XMLCoderElement.flatten()`.
At first, I was wondering what the `shuffled()` was for. I tried to get rid of it on its own, but the compiler didn't appreciate that very much when it came to `KeyedStorage.init<S>(_ sequence: S) where S: Sequence, S.Element == (Key, Value)`. Could this be a moment of ambiguity between `(Key,Value)` and `(key: Key, value: Value)`?
Ultimately, `mapValues` alone should do the trick, but I thought it might be nice to avoid another O(*n*) pass if not necessary.
Did `shuffled` have any other purpose than juggling types with the compiler?
> Use map instead of mapValues/shuffle in XMLCoderElement.flatten

- .swiftlint.yml
- Sources/XMLCoder/Auxiliaries/Box/BoolBox.swift
- Sources/XMLCoder/Auxiliaries/Box/DataBox.swift
- Sources/XMLCoder/Auxiliaries/Box/DateBox.swift
- Sources/XMLCoder/Auxiliaries/Box/DecimalBox.swift
- Sources/XMLCoder/Auxiliaries/Box/KeyedBox.swift
- Sources/XMLCoder/Auxiliaries/Box/SharedBox.swift
- Sources/XMLCoder/Auxiliaries/Box/StringBox.swift
- Sources/XMLCoder/Auxiliaries/Box/URLBox.swift
- Sources/XMLCoder/Auxiliaries/Box/UnkeyedBox.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/Box/BoolBoxTests.swift
- Tests/XMLCoderTests/Box/DataBoxTests.swift
- Tests/XMLCoderTests/Box/DateBoxTests.swift
- Tests/XMLCoderTests/Box/DecimalBoxTests.swift
- Tests/XMLCoderTests/Box/KeyedBoxTests.swift
- Tests/XMLCoderTests/Box/SharedBoxTests.swift
- Tests/XMLCoderTests/Box/StringBoxTests.swift
- Tests/XMLCoderTests/Box/URLBoxTests.swift
- Tests/XMLCoderTests/Box/UnkeyedBoxTests.swift
- Tests/XMLCoderTests/SpacePreserveTest.swift
- XMLCoder.xcodeproj/project.pbxproj
Fix an issue uncovered by MaxDesiatov/CoreXLSX#59. Also include slightly unrelated cleanups.
Resolves #94
> Fix decoding empty element as optional

- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Tests/XMLCoderTests/KeyDecodingStrategyTest.swift
- XMLCoder.xcodeproj/project.pbxproj
I found an issue with the `convertFromCapitalized` key decoding strategy which threw an error when the key had just one characted. This PR should fix the issue.
> Fixed a bug when decoding a key with one character only

- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/NamespaceTest.swift
An important case of empty sequences was broken in 0.5.0 as uncovered in MaxDesiatov/CoreXLSX#60 tests. This is now fixed and will be released ASAP as 0.5.1 hotfix.
> Fix decoding of empty sequences

- Sources/XMLCoder/Auxiliaries/Box/KeyedBox.swift
- Sources/XMLCoder/Auxiliaries/Box/SharedBox.swift
- Sources/XMLCoder/Auxiliaries/Box/UnkeyedBox.swift
- Sources/XMLCoder/Auxiliaries/KeyedStorage.swift
- Sources/XMLCoder/Auxiliaries/Metatypes.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Decoder/DecodingErrorExtension.swift
- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Decoder/XMLUnkeyedDecodingContainer.swift
- Sources/XMLCoder/Encoder/XMLKeyedEncodingContainer.swift
- Sources/XMLCoder/Encoder/XMLReferencingEncoder.swift
- Tests/XMLCoderTests/Box/KeyedBoxTests.swift
- Tests/XMLCoderTests/Box/UnkeyedBoxTests.swift
- Tests/XMLCoderTests/MixedContainerTest.swift
- XMLCoder.xcodeproj/project.pbxproj
- XMLCoder.xcodeproj/xcshareddata/xcbaselines/XMLCoder::XMLCoderTests.xcbaseline/76E090BF-7AFE-4988-A06A-3C423396A4A4.plist
`UnkeyedBox` is a wrapper for `[Box]`, the assumption is that adding direct `Box` conformance to `[Box]` would simplify things a bit. Also, `KeyedStorage` now always stores `[Box]` per key without any special handling for single items per key to simplify this even more. In addition, order of values is preserved for all keys as required for #91 and #25.
This should also unblock #101 providing unified handling for elements without any content and attributes.
By pure serendipity this also fixes tests introduced in #38.
> Replace UnkeyedBox with Array, refine KeyedStorage

- Sources/XMLCoder/Auxiliaries/String+Extensions.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Sources/XMLCoder/Encoder/XMLKeyedEncodingContainer.swift
- Tests/XMLCoderTests/KeyDecodingAndEncodingStrategyTests.swift
- Tests/XMLCoderTests/KeyDecodingStrategyTest.swift
- XMLCoder.xcodeproj/project.pbxproj
See: https://en.wikipedia.org/wiki/Letter_case#Special_case_styles
It would also be nice to make all the `convert...` functions declared under `KeyEncodingStrategy` and `KeyDecodingStrategy` public, so consumers can use them when performing a custom conversion.
I will be adding tests in case this contribution is desired.
> Add support for kebab-case KeyDecodingStrategy

- Sources/XMLCoder/Decoder/XMLDecoder.swift
Fixes a compiler warning; this is never mutated so it can be changed to `let`
> Change components variable from var to let

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/DynamicNodeDecodingTest.swift
- Tests/XMLCoderTests/DynamicNodeEncodingTest.swift
- Tests/XMLCoderTests/Minimal/BoxTreeTests.swift
This PR fixes https://github.com/MaxDesiatov/XMLCoder/issues/108 by replacing the unordered data structure used for storing the attributes (a Swift `Dictionary`) with an ordered data structure: an array of `Attribute` structs.
> Keep the order of the attributes during encoding operations

- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
This is just a typo fix but it _is_ public API.
> Fix typo: errorContextLenght -> errorContextLength

- Sources/XMLCoder/Auxiliaries/KeyedStorage.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/NestedChoiceTests.swift
In merging in #119, we fixed most but not quite all of #91! Decoding of _null_ choice elements (represented as enums with empty struct associated values on the Swift side) still results in errors. This PR adds a test to demonstrate and fixes this issue by wrapping each `NullBox` inside of a `SingleKeyedBox` at the `merge` phase (called by `transformToBoxTree`).
One of the main lessons from #119 was that we have to wrap choice elements in the decoding phase to hold onto their keys. The keys are needed for directing us to the correct branch of the do-catch pyramid used for decoding. 
```swift
private enum Entry: Equatable {
case run(Run)
case properties(Properties)
case br(Break)
}
extension Entry: Decodable {
private enum CodingKeys: String, XMLChoiceCodingKey {
case run, properties, br
} …
```
> Decoding choice elements that can hold empty structs 

- Tests/XMLCoderTests/RootLevelAttributeTest.swift
- XMLCoder.xcodeproj/project.pbxproj
Resolves #127. I think the plist encoding/decoding should be independent of the XML encoding phase. I have tried to reproduce just the relevant encoding phase and it seems to work.
> Root Level Attribute Encoding

- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/NestedChoiceArrayTest.swift
- XMLCoder.xcodeproj/project.pbxproj
- XMLCoder.xcodeproj/xcshareddata/xcbaselines/XMLCoder::XMLCoderTests.xcbaseline/76E090BF-7AFE-4988-A06A-3C423396A4A4.plist
I believe the structure in issue #122 provides the right use case for a `nestedUnkeyedContainer` (for key `Chapters`). As such I add a test case with the full proposed usage and a fix for `XMLKeyedDecodingContainer.nestedUnkeyedContainer` on the implementation side that allows the decoding of wrapped arrays of `enum` types.
The key lines on the user-side are within the `Decodable` implementation for `Book`, with decoding initializer using nesting syntax as follows:
```swift
extension Book: Decodable {
enum CodingKeys: String, CodingKey {
case title
case chapters
}
init(from decoder: Decoder) throws {
let container = try decoder.container(keyedBy: CodingKeys.self)
title = try container.decode(String.self, forKey: .title)
var chapters = [Chapter]()
if var chapterContainer = try? …
```
> Fix Decoding of Nested Arrays of Enums

- README.md
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Tests/XMLCoderTests/CombineTests.swift
- XMLCoder.xcodeproj/project.pbxproj
This enables use of `XMLDecoder` with Combine's `decode(_:decoder:)` operator by conditionally conforming to `TopLevelDecoder` when Combine is available.
I explored doing the same for `TopLevelEncoder`, but `XMLEncoder` currently requires `rootKey:` to be specified at encoding time, so it's not possible to provide an implementation of `encode(_:)` without some design around how to dynamically determine the root key to use.
> Conditionally conform to Combine.TopLevelDecoder

- pod.sh
The issue is not reproducible with CocoaPods 1.7.5. The workaround can be removed when CocoaPods 1.8.4 is released and this or later version is available on Azure Pipelines.
> Fix CocoaPods issue on Azure Pipelines

- Sources/XMLCoder/Auxiliaries/Box/KeyedBox.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/AttributedIntrinsicTest.swift
Restricts the special case usage of `"value"` OR `""` as a coding key, as implemented in #73 to just `""`. `"value"` resumes functioning as a normal coding key. 
As noted in #145, `"value"` is starting to collide awkwardly in one or two cases where it may be _implicit_ per the special case usage 
```swift
<value-containing>I am implicitly labeled</value-containing>
``` 
or _explicit_, as in 
```swift
<value-containing>
<value>I am explicitly labeled</value>
</value-containing>
``` 
With the change proposed, the latter example will be unambiguously captured by
```swift
struct ValueContaining: Codable {
let value: String
}
```
while the former is equivalent to
```swift
struct ValueContaining: Codable {
let value: String
enum CodingKeys: String, CodingKey {
case value = ""
}
}
```
This is a …
> Replace value intrinsic with empty string key

- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Tests/XMLCoderTests/MixedChoiceAndNonChoiceTests.swift
- Tests/XMLCoderTests/XCTestManifests.swift
Mirrors #154 
Fixes bugs 
1) Decoding multiple choice elements in the same Keyed Container.
2) Decoding choice elements after decoding regular keyed elements in the same container.
Case 1 refers to decoding implementations of the form: 
```swift
init(from decoder: Decoder) throws {
let container = try decoder.container(keyedBy: CodingKeys.self)
otherValue = try container.decode(String.self, forKey: .otherValue)
intOrString = try IntOrString(from: decoder)
}
```
where `IntOrString` is a choice coding element
<details><summary>(<code>IntOrString</code> defined as follows) </summary>
<p>
```swift 
enum IntOrString {
case int(Int)
case string(String)
}
extension IntOrString: Decodable {
enum CodingKeys: String, CodingKey {
case int
case string
}
init(from decoder: Decoder) throws {
let …
```
> Mixed choice/non-choice decoding

- Sources/XMLCoder/Auxiliaries/KeyedStorage.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/Minimal/BoxTreeTests.swift
- Tests/XMLCoderTests/Minimal/MixedContentTests.swift
Adding support for nodes with mixed content, where loose text nodes might coexist with other  node types. An example of this in the tests is: `<container>first<b>bold text</b>second</container>`.
This restructures the contents of nodes, so that raw text is always stored in a `""`-keyed node, which can occur multiple times if necessary. Previously all text nodes were appended together into the element's `value`, so their order relative to elements between them was lost.
> Support for mixed-content nodes

- XMLCoder.xcodeproj/project.pbxproj
> Use reverse-DNS notation for the bundle identifier

- Sources/XMLCoder/Auxiliaries/Box/KeyedBox.swift
- Sources/XMLCoder/Auxiliaries/KeyedStorage.swift
- Tests/XMLCoderTests/CDATATest.swift
> Fix CDATA issue

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/RootLevetExtraAttributesTests.swift
- XMLCoder.xcodeproj/project.pbxproj
Sometimes we want some attributes in the root node of our xml that don't should or need to be in the model, for example the attributes for the namespace or schema.
This pull request uses the existing attributes in the boxes to add those attributes to the root node.
Also, we can now infer the root node name instead of providing it in the encode method, making it optional in the API. 
I'm not sure if this is the best place, or add them as a configuration for the coders instead of use them all the time we call the `encode` method.
It would be nice if those attributes were moved to the coder configuration, so we could have the clean coding methods and looking more like the Apple JSON coders. What you think?
> Add support for root attributes propagation

- .vscode/settings.json
- .vscode/tasks.json
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/CDATATest.swift
> Encode only strings as CDATA

- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/CombineTests.swift
`TopLevelEncoder` implementation was added by #175. However, its method cannot be overridden. If it can be, we can use custom root key, root attributes, or header even when we use Combine-style like this:
```swift
final class MyEncoder: XMLEncoder {
override func encode<T>(_ value: T) throws -> Data where T : Encodable {
try self.encode(value, withRootKey: "foo", rootAttributes: nil, header: XMLHeader(version: 1.0, encoding: "UTF-8"))
}
}
```
So, I proposed the solution.
> Make TopLevelEncoder implementation overridable

- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Decoder/XMLDecoderImplementation.swift
- Tests/XMLCoderTests/Minimal/KeyedTests.swift
This will convert from `ALL_CAPS_SNAKE_CASE` to `camelCase`.
Previously, there was only snake_case, kebab-case, and first-letter-only Capitalised. To do ALL_CAPS, one needed to use a custom key decoding strategy.
I've been using this to make a decoder for [BeerXML](http://www.beerxml.com), which tends to have the keys capitalised.
> Add convert from UPPERCASE decoding key strategy

- README.md
- Sources/XMLCoder/Auxiliaries/String+Extensions.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Tests/XMLCoderTests/Auxiliary/String+ExtensionsTests.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/Minimal/NestedStringList.swift
- Tests/XMLCoderTests/Minimal/StringTests.swift
This updates the `XMLStackParser` to accept a parameter called `removeWhitespaceElements`.
The purpose of the `XMLStackParser` is to call the XML parser and create a tree of `XMLCoderElement` representing the structure of the parsed XML.
Assuming that XMLStackParser has `trimValueWhitespaces` set to `false`, when attempting to parse a nested data structure like the following:
```xml
<SomeType>
<nestedStringList>
<member>
<member>foo</member>
<member>bar</member>
</member>
<member>
<member>baz</member>
<member>qux</member>
</member>
</nestedStringList>
</SomeType>
```
... then there will multiple `XMLCoderElement`s in the tree which will have `elements` set to elements that are either:
a.  Purely whitespaced elements or
b.  The child elements
These purely whitespaced elements are …
> Implement `removeWhitespaceElements ` on `XMLDecoder`

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
Original description is in this issue:
https://github.com/MaxDesiatov/XMLCoder/issues/224
> Encode element with empty key, empty element, and attributes

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
The parameter was not used inside the method and only had one call-site
Please ignore if you are planning to use the parameter in some way.
All tests are passing
> Remove unneeded parameter `key`

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/SpacePreserveTest.swift
Hello everyone!
I found that the logic for trimming white-spaces (`trimValueWhitespaces`) may inadvertently remove white-spaces from inside the string value of the element, if `XMLParser` reports the content of a single element as multiple strings.  
This happens for example with non-ascii characters like German umlauts:
`Lösen` is split up and reported separately as `L` and `ösen`.
Or where we have "mixed" strings, e.g. containing a segment of Japanese or Chinese characters:
`Japanese 日本語` is split into `Japanese` and ` 日本語`.
If there's a white-space adjacent to the split, as in the Japanese example above, the white-space gets trimmed **before** it's joined together. Resulting in `Japanese日本語` without a space in the middle.
I added failing tests with the first commit.
---
see also: …
> Fix `trimValueWhitespaces` removing needed white-spaces

- Sources/XMLCoder/Auxiliaries/XMLStackParser.swift
- Sources/XMLCoder/Decoder/DecodingErrorExtension.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Tests/XMLCoderTests/Auxiliary/XMLElementTests.swift
- Tests/XMLCoderTests/Auxiliary/XMLStackParserTests.swift
- Tests/XMLCoderTests/Minimal/NestedStringList.swift
- Tests/XMLCoderTests/Minimal/StringTests.swift
This PR tends to some of the warnings generated by swiftlint.  
Please feel free to adjust if the changes don't work for you.
The FIXME on the test values in StringTests.swift:19 seems to actually be fixed somehow because the tests are passing without any adjustment.
> Remove some of the swiftlint generated warnings

- Tests/XMLCoderTests/SpacePreserveTest.swift
As mentioned in  https://github.com/MaxDesiatov/XMLCoder/pull/226#issuecomment-962542834 this test makes sure that strings containing xml entities surrounded with whitespaces are handled correctly.
> Add test for preserved spaces with xml entities

- Sources/XMLCoder/Auxiliaries/String+Extensions.swift
This patch is really very simple one, but I believe can be both a simplification on implementation and a perf improvement in the sense that as it is if we take for example as reference the implementation of [`trimmingCharacters`](https://github.com/apple/swift-corelibs-foundation/blob/34887cb2615e903cbe7ad428a538ee27be5a7d39/Sources/Foundation/NSString.swift#L1162) we note that it will do a lot extra work as allocating buffers or a whole new string maybe, when this only need a simple check that can exit early and also avoid those extra allocations. 
I'm not sure if is significant, because I cannot tell if this is used in hot paths within the project and also I didn't measure, so perf improvement is just a guess that makes sense to me, and since it was a simple change I thought in open the …
> Simplify string isAllWhitespace implementation

- Package.swift
Hi,
I would like to contribute fixing a recent warning.
The new Xcode 14 uses next SDKs as base: iOS 11.0, macOS 10.13, watchOS 4.0 and tvOS 11.0. Compiling in this Xcode shows a warning.
Handle this restrictions relying on swift version (which is also vinculated to each Xcode version).
Regards and comments welcomed
> Fix iOS 11 support warnings

- .github/workflows/main.yml
- Tests/XMLCoderTests/AdvancedFeatures/ErrorContextTest.swift
- test_xcodebuild.sh
The way the XML parser from Foundation treats errors differs between SDK versions, we have to handle this in our tests accordingly.
> Test with Xcode 14.0 and Swift 5.7

- README.md
- Sources/XMLCoder/Auxiliaries/Attribute.swift
- Sources/XMLCoder/Auxiliaries/Element.swift
- Sources/XMLCoder/Auxiliaries/ElementAndAttribute.swift
- Sources/XMLCoder/Auxiliaries/XMLHeader.swift
- Sources/XMLCoder/Decoder/DynamicNodeDecoding.swift
- Sources/XMLCoder/Decoder/XMLDecoder.swift
- Sources/XMLCoder/Encoder/DynamicNodeEncoding.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/AdvancedFeatures/PropertyWrappersTest.swift
- XMLCoder.xcodeproj/project.pbxproj
When viewing documentation published at https://swiftpackageindex.com/CoreOffice/XMLCoder/main/documentation/xmlcoder, I noticed that some of the doc comments are missing, and we made some of the protocols `public` by mistake. I've added doc comments with example code and update those protocols accordingly.
Additionally, tests and a section in `README.md` for recently added property wrappers were missing, that's fixed as well.
> Update doc comments, add `PropertyWrappersTest`

- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/CDATAMixedUsageTest.swift
- XMLCoder.xcodeproj/project.pbxproj
> Fix mixed CDATA usage

- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Encoder/XMLEncoder.swift
- Tests/XMLCoderTests/NodeEncodingStrategyTests.swift
Opts out of empty element shorthand.
---
I'm using XMLCoder to generate XML from my Swift data models for use in another system that doesn't handle the empty-elements, so I've added this option to allow generating XML that it can ingest. Not sure if `OutputFormatting` is the right place for this.
> Adds `.noEmptyElements` option to OutputFormatting

- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift
Consider enum with associated values, where some value is empty
```
enum Choice: Equatable, Codable {
case one
case two(Int)
case three(String, value: Int)
}
```
This PR fix decoding of such enum (while encoding is already worked as expected)
See new test in commit for details
Seems it also fixes #202
> Fix decoding of enum with associated values when enum case does not contain value

- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/AdvancedFeatures/DynamicNodeDecodingTest.swift
Fix case when XMLNodeDecoding wants to decode elementOrAttribute, but value is not present in XML
Was: silently treat missing of XML child as default value for string
Now: throws error
Fix error reporting when key not found for element or attribute #254
> Fix decoding of types conforming to XMLNodeDecoding

- Package.swift
This PR fixes a Xcode 15 SPM warning related to iOS/tvOS versions supported, which is the minimum version supported.
> Fix Xcode 15 SPM warning related to iOS 12, tvOS 12 support

- README.md
- Sources/XMLCoder/Auxiliaries/Utils.swift
- Sources/XMLCoder/Auxiliaries/XMLCoderElement.swift
- Sources/XMLCoder/Decoder/XMLChoiceDecodingContainer.swift
- Sources/XMLCoder/Decoder/XMLKeyedDecodingContainer.swift
- Tests/XMLCoderTests/AdvancedFeatures/InlinePropertyTests.swift
- Tests/XMLCoderTests/AdvancedFeatures/NestedChoiceTests.swift
- Tests/XMLCoderTests/AdvancedFeatures/SimpleChoiceTests.swift
- fix output for case when one of CodingKeys is empty string
- fix mirror decoding of encoded type where one of CodingKeys is empty string
> Empty codingkey encode decode output
